# -*- coding: utf-8 -*-
"""NickName.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15mhjq85IJJHZhHnjaRWeYEimT49mQjGA
"""

import random

def generate_nickname(hobbies, colors, movies):
    # Combine user inputs
    combined_inputs = hobbies + colors + movies

    # Shuffle the combined inputs
    random.shuffle(combined_inputs)

    # Generate a nickname based on the shuffled inputs
    nickname = "_".join(combined_inputs)

    return nickname

# Get user input for hobbies, colors, and movies
hobbies = input("Enter your hobbies (comma-separated): ").split(',')
colors = input("Enter your favorite colors (comma-separated): ").split(',')
movies = input("Enter your favorite movies (comma-separated): ").split(',')

# Generate and print the nickname
nickname = generate_nickname(hobbies, colors, movies)
print("Your suggested nickname is:", nickname)